# Generated by Django 5.2.8 on 2025-11-15 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='district_of_birth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='employer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='employer_department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='employer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='income_range',
            field=models.CharField(blank=True, choices=[('Below 300,000', 'Below 300,000'), ('300,000–600,000', '300,000–600,000'), ('600,000–1,000,000', '600,000–1,000,000'), ('Above 1,000,000', 'Above 1,000,000')], max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_fee_paid',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=12),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='nok_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='nok_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('SMS', 'SMS'), ('Call', 'Call'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp')], max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_saving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='member',
            name='source_of_income',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='tribe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='nok_relationship',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_account', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='SavingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='members.savingaccount')),
            ],
        ),
    ]
