# Generated by Django 5.2.8 on 2025-11-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='temp_password',
            field=models.BooleanField(default=True),
        ),
    ]
