# Generated by Django 5.2.8 on 2025-11-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='members.member')),
            ],
        ),
    ]
