# Generated by Django 5.2.8 on 2025-11-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_profile_pic_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='national_id_copy',
            field=models.FileField(blank=True, help_text='Upload National ID copy (PDF, PNG, JPG, JPEG).', null=True, upload_to='national_ids/'),
        ),
    ]
