# Generated by Django 5.2.8 on 2025-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_loan_loanguarantor_loanrepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_fee_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_saving',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
