# Generated by Django 5.2.8 on 2025-11-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_membership_fee_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload bank receipt (PDF, JPG, PNG)', null=True, upload_to='loan_receipts/'),
        ),
    ]
