# Generated by Django 5.2.8 on 2025-12-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco_name', models.CharField(default='Devroots SACCO', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system_logos/')),
                ('default_membership_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_loan_interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=10000, max_digits=15)),
                ('loan_repayment_period_days', models.IntegerField(default=90)),
                ('notifications_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personal_info', 'Updating Personal Information'), ('financial_guidance', 'Financial Literacy / Guidance'), ('service_issue', 'Service Issues'), ('transaction_error', 'Incorrect Deductions or Errors'), ('staff_behavior', 'Staff Behavior'), ('other', 'Other / Miscellaneous')], max_length=50)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='members.member')),
            ],
        ),
    ]
