# Generated by Django 5.2.8 on 2025-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_systemsetting_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
