# Generated by Django 5.2.8 on 2025-12-03 01:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_role_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='savingaccount',
            options={'ordering': ['-account_created']},
        ),
        migrations.AlterModelOptions(
            name='savingtransaction',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_fee_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
